### PR TITLE
Drop support of buf_redux / streaming input

### LINKED ISSUE #21: future-incompatibilities: buf_redux v0.8.4
```
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4
```
https://github.com/abonander/buf_redux/issues/23

### PR DESCRIPTION
**Pull request by gwenn**
Should fix #21 and #23

### CODE REVIEW

**Comment by gwenn** [comment]
Some rustdoc is not up to date like [here](https://github.com/gwenn/lemon-rs/pull/26/files#diff-3f786ccab1066df60ecf2d56744fa4fbc9b94efe78a12f66d0a5f986e81038baR37) but I will fix them later...

**Review by MarinPostma — APPROVED** [review]
Looks good!

**Comment by MarinPostma** [comment]
Actually, there is a drawback to this, the scanner is not allowed to own it's buffer. This is an issue when you want to store the parser

**Comment by MarinPostma** [comment]
I think we should let the scanner own the buffer and add store an offset to the current byte position, instead of re-slicing.

The buffer can be made generic over `T: AsRef<[u8]>`

**Comment by gwenn** [comment]
> I think we should let the scanner own the buffer and add store an offset to the current byte position, instead of re-slicing.

This solution should also help fixing #4

**Comment by gwenn** [comment]
With `input: AsRef<[u8]>`:
```
error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/lexer/scan.rs:115:25
    |
98  |     pub fn scan(&mut self) -> ScanResult<'_, S::TokenType, S::Error> {
    |                 - let's call the lifetime of this reference `'1`
...
104 |                 let data = &self.input.as_ref()[self.offset..];
    |                             ------------------- immutable borrow occurs here
...
115 |                         self.consume(amt);
    |                         ^^^^^^^^^^^^^^^^^ mutable borrow occurs here
...
120 |                         return Ok(tok);
    |                                ------- returning this value requires that `self.input` is borrowed for `'1`
```
I should be able to fix `consume` but not the lifetime issue...

**Comment by gwenn** [comment]
> I think we should let the scanner own the buffer and add store an offset to the current byte position, instead of re-slicing.

I had to do the contrary in [611b94f](https://github.com/gwenn/lemon-rs/pull/26/commits/611b94f2fdcb5f7bd9c7fe960d33f167fb30c195): the input is now passed as a parameter to the `scan` method and the parser now keeps a reference to the input (to make the borrow checker happy in `Parser::next`).

**Pull request merged**
